# Generated by Django 4.2.16 on 2025-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('DOP', models.DateField()),
                ('Role', models.CharField(default='bowler', max_length=100)),
                ('contact', models.IntegerField(max_length=14)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
